### ISSUE TITLE
Plugin warns user about false blocking popup

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/intellij-plugin#117]
When `Version Control` notification is visible and you do an operation using Copilot, there is a notification about blocking popup which is a false warning.
![Screenshot 2024-10-04 at 12 28 04](https://github.com/user-attachments/assets/1d503930-a5d4-4298-a036-93b4d2d156c8)
![Screenshot 2024-10-04 at 12 27 58](https://github.com/user-attachments/assets/c75bb3a5-6986-40f4-89c0-6d7479487eed)

**Comment by MarcinVaadin** [comment]
Popup present while duplicating component - should not be present if not creating new files (modifying vcs).

**Comment by MarcinVaadin** [comment]
I cannot reproduce above. Please provide example project with reproducible scenario.
