### ISSUE TITLE
[Error report] com.intellij.diagnostic.PluginException: Write access is allowed inside write-action only (see Application.runWriteAction())

### ISSUE THREAD

**Issue by ettiennelr** [vaadin/intellij-plugin#198]
Plugin version: **1.4.1**
IDE version: **IntelliJ IDEA 2024.3**
OS: **Mac OS X**

Stacktrace:
```
com.intellij.diagnostic.PluginException: Write access is allowed inside write-action only (see Application.runWriteAction())

**Comment by MarcinVaadin** [comment]
Thanks for the issue, please create new one with whole stacktrace, this one looks truncated and do not provide any information about the exception.
