### ISSUE TITLE
2024.2 Compatibility

### ISSUE THREAD

**Issue by apklein** [vaadin/intellij-plugin#53]
I started yesterday a copilot trial and 10 minutes later I updated to latest IntelliJ Idea 2024.2 and the plugin stopped working... how I can reset my trial? when will be released 2024.2 plugin version?

Best Regards,
Ariel Pablo Klein

**Comment by MarcinVaadin** [comment]
2024.2 will be supported in latest 1.2.0 plugin version.

**Comment by MarcinVaadin** [comment]
> how I can reset my trial

What kind of "trial" you mean? 3 day test period or 90 day trial?
