### ISSUE TITLE
Debug using Hotswap should be shown in services menu

### ISSUE THREAD

**Issue by Artur-** [vaadin/intellij-plugin#76]
![image](https://github.com/user-attachments/assets/401061e6-3cd5-47df-a861-93d500567ea6)

This is currently missing the HotswapAgent option

**Comment by MarcinVaadin** [comment]
Not sure how to put it there. Those services are actually run configurations:

<img width="533" alt="image" src="https://github.com/user-attachments/assets/8f71af28-eea6-48dd-8ec7-724fe9eea4bc">

When you run Debug with HotSwap you actually reuse existing run configuration with just different "runner":

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/b8ff1078-e8a1-4034-b7b2-052ebde649c0">

**Comment by MarcinVaadin** [comment]
Or maybe you mean the context menu only...
